// Code generated by protoc-gen-go. DO NOT EDIT.
// source: migration.proto

/*
Package migration is a generated protocol buffer package.

It is generated from these files:
	migration.proto

It has these top-level messages:
	Empty
	HealthCheckResponse
	PauseRequest
	PauseResponse
	ResumeResponse
	MigrateResponse
	UnmigrateResponse
*/
package migration

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN   HealthCheckResponse_Status = 0
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 1
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 2
)

var HealthCheckResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEALTHY",
	2: "UNHEALTHY",
}
var HealthCheckResponse_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"HEALTHY":   1,
	"UNHEALTHY": 2,
}

func (x HealthCheckResponse_Status) String() string {
	return proto.EnumName(HealthCheckResponse_Status_name, int32(x))
}
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthCheckResponse struct {
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,enum=migration.HealthCheckResponse_Status" json:"status,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type PauseRequest struct {
	Timeout int32 `protobuf:"varint,1,opt,name=timeout" json:"timeout,omitempty"`
	Expiry  int32 `protobuf:"varint,2,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *PauseRequest) Reset()                    { *m = PauseRequest{} }
func (m *PauseRequest) String() string            { return proto.CompactTextString(m) }
func (*PauseRequest) ProtoMessage()               {}
func (*PauseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PauseRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *PauseRequest) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type PauseResponse struct {
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ExpiresAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt" json:"expires_at,omitempty"`
}

func (m *PauseResponse) Reset()                    { *m = PauseResponse{} }
func (m *PauseResponse) String() string            { return proto.CompactTextString(m) }
func (*PauseResponse) ProtoMessage()               {}
func (*PauseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PauseResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PauseResponse) GetExpiresAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type ResumeResponse struct {
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *ResumeResponse) Reset()                    { *m = ResumeResponse{} }
func (m *ResumeResponse) String() string            { return proto.CompactTextString(m) }
func (*ResumeResponse) ProtoMessage()               {}
func (*ResumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResumeResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type MigrateResponse struct {
	MigratingTo string                     `protobuf:"bytes,1,opt,name=migrating_to,json=migratingTo" json:"migrating_to,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *MigrateResponse) Reset()                    { *m = MigrateResponse{} }
func (m *MigrateResponse) String() string            { return proto.CompactTextString(m) }
func (*MigrateResponse) ProtoMessage()               {}
func (*MigrateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MigrateResponse) GetMigratingTo() string {
	if m != nil {
		return m.MigratingTo
	}
	return ""
}

func (m *MigrateResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UnmigrateResponse struct {
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *UnmigrateResponse) Reset()                    { *m = UnmigrateResponse{} }
func (m *UnmigrateResponse) String() string            { return proto.CompactTextString(m) }
func (*UnmigrateResponse) ProtoMessage()               {}
func (*UnmigrateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UnmigrateResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "migration.Empty")
	proto.RegisterType((*HealthCheckResponse)(nil), "migration.HealthCheckResponse")
	proto.RegisterType((*PauseRequest)(nil), "migration.PauseRequest")
	proto.RegisterType((*PauseResponse)(nil), "migration.PauseResponse")
	proto.RegisterType((*ResumeResponse)(nil), "migration.ResumeResponse")
	proto.RegisterType((*MigrateResponse)(nil), "migration.MigrateResponse")
	proto.RegisterType((*UnmigrateResponse)(nil), "migration.UnmigrateResponse")
	proto.RegisterEnum("migration.HealthCheckResponse_Status", HealthCheckResponse_Status_name, HealthCheckResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Migration service

type MigrationClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResumeResponse, error)
	Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MigrateResponse, error)
	Unmigrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnmigrateResponse, error)
}

type migrationClient struct {
	cc *grpc.ClientConn
}

func NewMigrationClient(cc *grpc.ClientConn) MigrationClient {
	return &migrationClient{cc}
}

func (c *migrationClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/migration.Migration/health_check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	out := new(PauseResponse)
	err := grpc.Invoke(ctx, "/migration.Migration/pause", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := grpc.Invoke(ctx, "/migration.Migration/resume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MigrateResponse, error) {
	out := new(MigrateResponse)
	err := grpc.Invoke(ctx, "/migration.Migration/migrate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) Unmigrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnmigrateResponse, error) {
	out := new(UnmigrateResponse)
	err := grpc.Invoke(ctx, "/migration.Migration/unmigrate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Migration service

type MigrationServer interface {
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	Resume(context.Context, *Empty) (*ResumeResponse, error)
	Migrate(context.Context, *Empty) (*MigrateResponse, error)
	Unmigrate(context.Context, *Empty) (*UnmigrateResponse, error)
}

func RegisterMigrationServer(s *grpc.Server, srv MigrationServer) {
	s.RegisterService(&_Migration_serviceDesc, srv)
}

func _Migration_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migration.Migration/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migration.Migration/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migration.Migration/Resume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Resume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migration.Migration/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Migrate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_Unmigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Unmigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migration.Migration/Unmigrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Unmigrate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Migration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "migration.Migration",
	HandlerType: (*MigrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "health_check",
			Handler:    _Migration_HealthCheck_Handler,
		},
		{
			MethodName: "pause",
			Handler:    _Migration_Pause_Handler,
		},
		{
			MethodName: "resume",
			Handler:    _Migration_Resume_Handler,
		},
		{
			MethodName: "migrate",
			Handler:    _Migration_Migrate_Handler,
		},
		{
			MethodName: "unmigrate",
			Handler:    _Migration_Unmigrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migration.proto",
}

func init() { proto.RegisterFile("migration.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x4d, 0x02, 0x4d, 0xc8, 0xed, 0xa7, 0x23, 0x68, 0x0c, 0xe2, 0xc7, 0x80, 0xe0, 0x53, 0x8a,
	0xf5, 0x41, 0x0a, 0x16, 0xac, 0x52, 0x28, 0xd4, 0x46, 0x89, 0x2d, 0xe2, 0x53, 0x49, 0xeb, 0x98,
	0x06, 0x9b, 0x4c, 0xcc, 0x4c, 0xc0, 0xfe, 0x80, 0x65, 0xff, 0xd6, 0xfe, 0xb4, 0x25, 0x93, 0x49,
	0x9b, 0x6d, 0xbb, 0xbb, 0xec, 0xb2, 0x8f, 0xf7, 0xcc, 0x39, 0xf7, 0xde, 0x39, 0xf7, 0x40, 0x3b,
	0x0a, 0x83, 0xd4, 0xe7, 0x21, 0x8d, 0x9d, 0x24, 0xa5, 0x9c, 0x22, 0x73, 0x07, 0xd8, 0x2f, 0x03,
	0x4a, 0x83, 0x0d, 0xe9, 0x8a, 0x87, 0x65, 0xf6, 0xa7, 0xcb, 0xc3, 0x88, 0x30, 0xee, 0x47, 0x49,
	0xc1, 0xc5, 0x06, 0xd4, 0x46, 0x51, 0xc2, 0xb7, 0xf8, 0x5c, 0x85, 0xc7, 0x63, 0xe2, 0x6f, 0xf8,
	0xfa, 0xcb, 0x9a, 0xac, 0xfe, 0x7a, 0x84, 0x25, 0x34, 0x66, 0x04, 0x0d, 0x40, 0x67, 0xdc, 0xe7,
	0x19, 0xb3, 0xd4, 0x57, 0xea, 0xdb, 0x56, 0xef, 0x8d, 0xb3, 0x1f, 0x77, 0x82, 0xef, 0xfc, 0x10,
	0x64, 0x4f, 0x8a, 0xf0, 0x3b, 0xd0, 0x0b, 0x04, 0xd5, 0xc1, 0x98, 0xbb, 0x13, 0xf7, 0xdb, 0x4f,
	0xb7, 0xa3, 0xe4, 0xc5, 0x78, 0x34, 0xfc, 0x3a, 0x1b, 0xff, 0xea, 0xa8, 0xa8, 0x09, 0xe6, 0xdc,
	0x2d, 0x4b, 0x0d, 0x7f, 0x82, 0xc6, 0x77, 0x3f, 0x63, 0xc4, 0x23, 0xff, 0x32, 0xc2, 0x38, 0xb2,
	0xc0, 0xc8, 0xb7, 0xa6, 0x19, 0x17, 0x2b, 0xd4, 0xbc, 0xb2, 0x44, 0x4f, 0x40, 0x27, 0xff, 0x93,
	0x30, 0xdd, 0x5a, 0x9a, 0x78, 0x90, 0x15, 0x3e, 0x53, 0xa1, 0x29, 0x5b, 0xc8, 0x5f, 0xf4, 0x01,
	0x56, 0x29, 0xf1, 0x39, 0xf9, 0xbd, 0xf0, 0x8b, 0x36, 0xf5, 0x9e, 0xed, 0x14, 0xe6, 0x38, 0xa5,
	0x39, 0xce, 0xac, 0x34, 0xc7, 0x33, 0x25, 0x7b, 0xc8, 0x73, 0xa9, 0x68, 0x4b, 0x58, 0x2e, 0xd5,
	0x6e, 0x97, 0x4a, 0xf6, 0x90, 0xe3, 0x09, 0xb4, 0x3c, 0xc2, 0xb2, 0xe8, 0x21, 0xf6, 0xc0, 0x14,
	0xda, 0x53, 0xe1, 0xfc, 0xbe, 0xdb, 0x6b, 0x68, 0xc8, 0x63, 0xc4, 0xc1, 0x82, 0x53, 0xd1, 0xcf,
	0xf4, 0xea, 0x3b, 0x6c, 0x46, 0x0f, 0x06, 0x6a, 0x77, 0x19, 0xe8, 0xc2, 0xa3, 0x79, 0x1c, 0x1d,
	0x8c, 0xbc, 0xff, 0x07, 0x7a, 0x17, 0x1a, 0x98, 0xd3, 0x32, 0x3b, 0xe8, 0x33, 0x34, 0xd6, 0x22,
	0x3e, 0x8b, 0x55, 0x9e, 0x1f, 0xd4, 0xa9, 0xe4, 0x4a, 0x24, 0xd2, 0x7e, 0x71, 0x73, 0xd2, 0xb0,
	0x82, 0x3e, 0x42, 0x2d, 0xc9, 0xcf, 0x8c, 0x9e, 0x56, 0xa8, 0xd5, 0xec, 0xd8, 0xd6, 0xf1, 0xc3,
	0x4e, 0xfd, 0x01, 0xf4, 0x54, 0x5c, 0xe7, 0xc4, 0xec, 0x67, 0x15, 0xe4, 0xea, 0x09, 0xb1, 0x82,
	0xfa, 0x60, 0x48, 0x5b, 0x4e, 0x28, 0xed, 0x0a, 0x72, 0x70, 0x2f, 0xac, 0xa0, 0x01, 0x98, 0x59,
	0x7c, 0xbd, 0xf8, 0x79, 0x05, 0x39, 0xf2, 0x1e, 0x2b, 0x4b, 0x5d, 0x38, 0xfc, 0xfe, 0x32, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0xea, 0xde, 0x72, 0xf3, 0x03, 0x00, 0x00,
}
