#!/usr/bin/env bash
# Starts a cluster, booting into a bash session inside pg01 that on exit will
# kill and clean-up the containers.

# run-container => prints <container-id>
function run-container() {
  docker run \
    --name "$1" \
    --hostname "$1" \
    --privileged \
    --detach \
    --publish-all \
    --volume "$(git rev-parse --show-toplevel):/pgsql-cluster-manager" \
    --volume "/var/run/docker.sock:/var/run/docker.sock" \
    gocardless/postgres-member \
    sh -c "while :; do sleep 1; done"
}

docker build -t gocardless/postgres-member .
docker rm -f pg01 pg02 pg03

PG01=$(run-container pg01)
PG02=$(run-container pg02)
PG03=$(run-container pg03)

docker exec --detach pg01 /bin/start-cluster "$PG01" "$PG02" "$PG03"
docker exec --detach pg02 /bin/start-cluster "$PG01" "$PG02" "$PG03"
docker exec --detach pg03 /bin/start-cluster "$PG01" "$PG02" "$PG03"

docker exec -it pg01 /bin/bash

docker kill pg01 pg02 pg03
docker rm pg01 pg02 pg03
